### ISSUE TITLE
How to modify?

### ISSUE THREAD

**Issue by alexmisaila2** [tastyForReal/pianotiles2web#3]
Hi, how I can edit the game assets? I found that some file codes are obfuscated (didn't found a working deobfuscator). I would like to implement the game in cocos but isn't possible. 
It's possible to make this fully working? Like editting the ads settings and all that... Seems to be useless as it is now

**Comment by tastyForReal** [comment]
Restoring or recreating this game from scratch is infeasible due to the obfuscated code. The de-obfuscated code would comprise over 80,000 lines, making a complete recreation a monumental task. While technically possible, it would be exceptionally challenging. Modifications are limited to assets outside the JavaScript files. I considered a personal recreation, but ultimately concluded it was impractical.
